# on:
#   schedule:
#     - cron: "0 0 * * 0"
on:
  push:
    branches:
      - gh-actions
name: generate-securities

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.x
      - uses: actions/checkout@v3

      # Get values for cache paths to be used in later steps
      - id: cache-paths
        run: |
          echo "::set-output name=go-cache::$(go env GOCACHE)"
          echo "::set-output name=go-mod-cache::$(go env GOMODCACHE)"
      - name: Cache go modules
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.cache-paths.outputs.go-cache }}
            ${{ steps.cache-paths.outputs.go-mod-cache }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Generate securities list
        run: go run ./scripts/generate_securities.go && go fmt ./twstock/securities_GENERATED.go

      - name: Check securities list changed
        id: check_list_changed
        shell: bash
        run: git diff --quiet --exit-code; code=$?; echo "::set-output name=changed::${code}"; (exit 0)

      - name: Create Pull Request
        id: cpr
        shell: bash
        if: steps.check_list_changed.outputs.changed == 1
        run: echo "Create Pull Request"
