# on:
#   schedule:
#     - cron: "0 0 * * 0"
on:
  push:
    branches:
      - gh-actions
name: generate-securities

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.x
      - uses: actions/checkout@v3

      # Get values for cache paths to be used in later steps
      - id: cache-paths
        run: |
          echo "::set-output name=go-cache::$(go env GOCACHE)"
          echo "::set-output name=go-mod-cache::$(go env GOMODCACHE)"
      - name: Cache go modules
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.cache-paths.outputs.go-cache }}
            ${{ steps.cache-paths.outputs.go-mod-cache }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Generate securities list
        run: |
          go run ./scripts/generate_securities.go &&
          mv /tmp/securities_GENERATED.go ./twstock/securities_GENERATED.go &&
          go fmt ./twstock/securities_GENERATED.go

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.2

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
