on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: tests

env:
  GO111MODULE: on

concurrency:
  group: "tests-${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  test:
    permissions:
      actions: write # for styfle/cancel-workflow-action to cancel/stop running workflows
      contents: read # for actions/checkout to fetch code
    strategy:
      matrix:
        go-version: [1.x, 1.21.x]
        platform: [ubuntu-latest]
        include:
          # only update test coverage stats with the most recent go version on linux
          - go-version: 1.x
            platform: ubuntu-latest
            update-coverage: true
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Ensure go generate produces a zero diff
        shell: bash
        run: go generate -x ./... && git diff --exit-code; code=$?; git checkout -- .; (exit $code)

      - name: Run go integration test
        run: go test -p 1 -v ./test/integration

      - name: Run go test
        run: go test -v -race -coverprofile coverage.txt ./twstock

      - name: Upload coverage to Codecov
        if: ${{ matrix.update-coverage }}
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 #v4.5.0
